### ISSUE TITLE
i3 config

### ISSUE THREAD

**Issue by janbaer** [lidel/linux-on-huawei-matebook-x-2017#2]
Could you please document how you configured your i3 config with mapping of all the fn keys (volume, light etc.). I looked in your dot files repo but I couldn't find any settings for that? Can you use the function keys? When yes, which are working and which not? Thanks!

**Comment by lidel** [comment]
My i3 config is in [dotfiles/.i3](https://github.com/lidel/dotfiles/tree/master/.i3). Due to legacy reasons I keep some key bindings in [.xbindkeysrc](https://github.com/lidel/dotfiles/blob/master/.xbindkeysrc), but these are often customized per machine and not tracked by git. I don't think these are useful for anyone but me :)

As for Matebook X: unfortunately hardware buttons do not work yet (`xev` do not register anything).
These keys probably require kernel support like ones in Sony Vaio did. 

For now I use different shortcuts for volume (via [pa-volume-ctl.sh](https://github.com/lidel/dotfiles/blob/master/bin/pa-volume-ctl.sh)) 
and screen brightness control (see https://github.com/lidel/linux-on-huawei-matebook-x-2017/issues/3).

**Comment by lidel** [comment]
@janbaer  just fyi I've fixed backlight control and created simple script for OSD feedback:

- https://github.com/lidel/linux-on-huawei-matebook-x-2017#display-backlight
-  https://github.com/lidel/dotfiles/blob/master/bin/backlight-ctl.sh

**Comment by janbaer** [comment]
Thanks a lot!
