### ISSUE TITLE
Touchscreen support is not clear ?

### ISSUE THREAD

**Issue by hualet** [lidel/linux-on-huawei-matebook-x-2017#7]
I can't see anything about the touchscreen support, is it working fine?

**Comment by edvwib** [comment]
There seems to be some confusion about what device this repository is documenting. This repository is documenting the MateBook X, which has no touchscreen. 

What i believe this issue is referring to is the MateBook X **Pro**, which has a touchscreen as well as a fan (#6), which is probably the same confusion as in this issue.

**Comment by hualet** [comment]
> There seems to be some confusion about what device this repository is documenting. This repository is documenting the MateBook X, which has no touchscreen.
> 
> What i believe this issue is referring to is the MateBook X **Pro**, which has a touchscreen as well as a fan (#6), which is probably the same confusion as in this issue.

Sorry, my bad.
